config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "covid", to: 'pages#covid'
  get "fancier", to: 'pages#fancier'
  get "freelance", to: 'pages#freelance'
  get "replastic", to: 'pages#replastic'
  get "fonts", to: 'pages#fonts'
  get "thirtydays", to: 'pages#thirtydays'
  get "univers", to: 'pages#univers'
  resources :messages, only: [ :create ]
  resources :posts do
    member do
      put "like" => "posts#like"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :note, :presence => true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
end

app/models/session.rb
class Session < ApplicationRecord
  acts_as_voter
end

app/models/voting_session.rb
class VotingSession < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
      flash[:alert] = 'Message sent!'
    else
      redirect_to root_path
      flash[:alert] = 'Message was empty! Nothing was sent. :('
    end
  end

  private

  def message_params
    params.require(:message).permit(:note)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @home_page = true
    session[:voting_id] = request.remote_ip
    @voter = Session.find_or_create_by(ip: session[:voting_id])
    @message = Message.new
  end

  def covid
  end

  def fancier
  end

  def thirtydays
  end

  def replastic
  end

  def fonts
  end

  def freelance
  end

  def univers
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def like
    @post = Post.find(params[:id])
    session[:voting_id] = request.remote_ip
    @voter = Session.find_or_create_by(ip: session[:voting_id])
    if @voter.voted_for? @post
      @post.unliked_by @voter
    else
      @post.liked_by @voter
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/pages/covid.html.erb
<header class="home-header project-head">
  <%= link_to root_path do %>
    <%=  image_tag("logo1.png", class: "logo") %>
  <% end %>
  <ul class="links page-links">
    <li> <a target=”_blank” href="https://www.linkedin.com/in/meghanxmartin/"><i aria-label="linkedin" class="fab fa-linkedin-in"></i></a> </li>
    <li> <a target=”_blank” href="https://twitter.com/meghanxmartin"><i aria-label="twitter" class="fab fa-twitter"></i></a> </li>
    <li> <a target=”_blank” href="https://github.com/meghanmartin995"><i aria-label="github" class="fab fa-github"></i></a> </li>
    <li> <a target=”_blank” href="https://dribbble.com/ziganka"><i aria-label="dribbble" class="fab fa-dribbble"></i></a> </li>
  </ul>
</header>

<header class="project-header">
  <%=  image_tag("cse1.png", alt: "screenshot of project", class: "covid-img img1 justify") %>
  <%=  image_tag("covid-M.svg", alt: "name of project", class: "covid-M img2 justify") %>
  <div class="details">
    <p>2020 (Present)</p>
    <p>UX/UI Design | Research software</p>
  </div>
</header>

<section class="project-content">
  <div class="summary">
    <h2>Simplifying the research process</h2>
    <p class="summary-text">designed an application for researchers that brings the time of digesting COVID-19 research from minutes to less than 30 seconds</p>
  </div>
  <div class="project-role">
    <h3>Context</h3>
    <p><a target=”_blank” href="https://covid-science-engine-prototype.herokuapp.com/">live open source application</a> currently being used by COVID-19 researchers in the field</p>
    <h3 class="role">Role</h3>
    <p>sole UI/UX designer under the lead of COVID-19 researcher, led front end development team for implementation. I built the style guide and UI library that was implemented in React</p>
    <p class="team">The team: two virologists, three front end developers, one backend developer, two machine learning data scientists and one designer (me).</p>
  </div>
</section>

<section class="final-design">
  <%=  image_tag("covid-mock.svg", alt: "mockup of project", class: "") %>
  <p>the final design</p>
</section>

<section class="problem">
  <h2>the problem ✍️</h2>
  <p>The core problem we are trying to solve is <span>reducing the time it takes for COVID-19 researchers to digest research papers. </span>With human and machine intelligence, we are condensing large research papers into main key findings, methods, context and molecular targets. The design challenge is how to present this information in a way that’s quickly digestable.</p>
  <!-- <h2>design <br> process 👩‍💻💭</h2>
  <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p> -->
</section>
<section class="final-design prob covid-prob">
 <%= image_tag("research.png") %>
  <p style="width: 70%; margin: 30px auto 0 auto; max-width: 1100px;"><span>Primary research finding from COVID-19 researchers:</span> the time allotted to digest one paper is 10+ minutes while key information needed is the article’s title, key findings, who/where, targets, context, models and methods (modelling, sequence, simulation, calculation). Time to digest this information and to conduct R&D would be reduced dramatically if this information was summarized at the beginning of the paper.</p>
</section>
  <h2 class="decisions-text problem" style="margin-bottom: 20px; font-family: Proxima Nova Bold;">design <br> decisions 👩‍💻</h2>
<section class="decisions">
  <%= image_tag("covid-1.svg", class: "covid1") %>
  <div class="finding" style="align-self: center">
    <%= image_tag("marker-1.svg") %>
    <p>Researchers expressed the need for a clean UI that condenses dense amounts of information into a quickly scannable interface. I chose to include a toggle for less and more information to allow for scrolling of the page without the need to click through to understand the research more deeply. Aesthetics were largely sacrificed for usability and readability.</p>
  </div>
  <div class="finding2 finding" style="align-self: center">
    <%= image_tag("marker-2.svg") %>
    <p>We needed to create an admin interface to accept and reject research summaries. I designed this interface with the intention of reusing components from the public interface to save development time. I included large indicators of red and green to quickly show to the admin the state of each research paper. </p>
  </div>
  <%= image_tag("covid-2.svg", class: "covid2") %>
  <%= image_tag("covid-3.svg", class: "covid3") %>
  <div class="finding3 finding" style="align-self: center">
    <%= image_tag("marker-3.svg") %>
    <p>I took design references from Google, Wikipedia and ResearchGate to develop an interface that would be familiar and trusted by researchers. The colors, font, font size ratios, spacing and overall feel of the UI was influenced from these sources that researchers already use on a day to day basis.</p>
  </div>
</section>
<section class="final-design">
  <%=  image_tag("form.svg", alt: "mockup of form", class: "") %>
  <p>uploading a research article</p>
</section>
<section class="problem">
  <h2>what i've <br>learned 📚</h2>
  <p>I really enjoyed working with the team of developers on this project and I learned a lot from their different expertises to grow as a designer. Sebastian, a front end dev on the team, taught me a lot about accessibility and React. Mat, the backend developer, taught me a lot about thinking from a future perspective on dev decisions to scale the project. From also having a dev perspective, I was able to keep the design very lean and minimal and optimize for reusability. The biggest challenge as a designer was keeping the design as lean as possible and sacrificing aesthetics for usability in many cases. Moving forward, we are testing the product on COVID-19 researchers and designing and building features based on demand.</p>
</section>
<section class="final-design">
  <%=  image_tag("style.svg", alt: "part of style guide", class: "") %>
</section>

<footer class="project-footer">
  <%= link_to("previous project", replastic_path) %>
  <a href="javascript:window.scrollTo(0,0);" style="cursor: pointer; text-decoration: none;" id="myBtn" title="Go to top">back to top</a>
  <%= link_to("next project", fancier_path) %>
</footer>

app/views/pages/cuzu.html.erb
<header class="project-header fancier">
  <%=  image_tag("fancier-img.png", alt: "screenshot of project", class: "fancier-img img1 justify") %>
  <%=  image_tag("fancier-M.svg", alt: "name of project", class: "fancier-M img2 justify") %>
  <div class="details">
    <p>2020</p>
    <p>UI Design | Productivity Software</p>
  </div>
</header>

<section class="project-content">
  <div class="summary">
    <h2>Designing a sustainable ecommerce experience</h2>
    <p class="summary-text">designed and shipped a social marketplace that creates a unique experience for shopping and selling pre-loved festival outfits </p>
  </div>
  <div class="project-role">
    <h3>Context</h3>
    <p><a target=”_blank” href="http://www.getfancier.com/">live application</a>, only with test users. you can watch me pitch fancier to a live audience <a target=”_blank” href="https://www.youtube.com/watch?v=Opy7Ur7keEc&feature=youtu.be">here.</a></p>
    <h3 class="role">Role</h3>
    <p>sole UI designer, part of full stack development team during Le Wagon’s fullstack coding bootcamp</p>
    <p class="team">The team: four fullstack developers, including myself.</p>
  </div>
</section>
<section class="final-design">
  <%=  image_tag("", alt: "mockup of project", class: "") %>
  <p>the final product</p>
</section>

app/views/pages/fancier.html.erb
<header class="home-header project-head">
  <%= link_to root_path do %>
    <%=  image_tag("logo1.png", class: "logo") %>
  <% end %>
  <ul class="links page-links">
    <li> <a target=”_blank” href="https://www.linkedin.com/in/meghanxmartin/"><i aria-label="linkedin" class="fab fa-linkedin-in"></i></a> </li>
    <li> <a target=”_blank” href="https://twitter.com/meghanxmartin"><i aria-label="twitter" class="fab fa-twitter"></i></a> </li>
    <li> <a target=”_blank” href="https://github.com/meghanmartin995"><i aria-label="github" class="fab fa-github"></i></a> </li>
    <li> <a target=”_blank” href="https://dribbble.com/ziganka"><i aria-label="dribbble" class="fab fa-dribbble"></i></a> </li>
  </ul>
</header>

<header class="project-header fancier">
  <%=  image_tag("xfancier2.png", alt: "screenshot of project", class: "fancier-img1 img1 justify") %>
  <%=  image_tag("fanciermarks2.svg", alt: "name of project", class: "fancier-M img2 justify") %>
  <div class="details">
    <p>2020</p>
    <p>UI Design | Ecommerce Platform</p>
  </div>
</header>

<section class="project-content">
  <div class="summary">
    <h2>Designing a sustainable ecommerce experience</h2>
    <p class="summary-text">designed and shipped a social marketplace that creates a unique experience for shopping and selling pre-loved festival outfits </p>
  </div>
  <div class="project-role">
    <h3>Context</h3>
    <p><a target=”_blank” href="http://www.getfancier.com/">live application</a>, only with test users. you can watch me pitch Fancier to a live audience <a target=”_blank” href="https://vimeo.com/441072361">here.</a></p>
    <h3 class="role">Role</h3>
    <p>sole UI designer, part of full stack development team during Le Wagon’s fullstack coding bootcamp</p>
    <p class="team">The team: four fullstack developers: Laura Aunion, Katy Link, Kendrikc Rambal and myself</p>
  </div>
</section>
<section class="final-design">
  <%=  image_tag("f.gif", alt: "mockup of project", class: "") %>
  <p>the final product</p>
</section>
<section class="problem">
  <h2>the problem ✍️</h2>
  <p>The core problem we are trying to solve is <span>unsustainability of festival clothing in the European market </span>clothing is bought from fast fashion chains and often only worn once. It’s challenging for festival goers to find something unique that is both at a reasonable price point and sustainable. The design challenge was to create a marketplace that would address this problem.</p>
</section>

<section class="final-design prob">
 <%= image_tag("fresearch.png") %>
  <p style="width: 70%; margin: 30px auto 0 auto; max-width: 1100px;">competitor analysis</p>
</section>

<section class="problem">
  <h2>design process 👩‍💻</h2>
  <p>As a team of four developers, we identified the core problem we wanted to tackle was unsustainability in fast fashion in regards to festival shopping. We first interviewed users who frequented festivals to understand their shopping behaviors. We researched into retail competitors in the festival market and explored potential solutions for a sustainable alternative. In the European sustainable fashion landscape, we found that there were only high end options or resellers with a large generic offering. we wanted to be low cost alternative that met the unique demand of festival shoppers. we sketched out the first versions of Fancier, which we tested on our target market. After getting feedback I created wireframes which I soon converted into high fidelity prototypes that our team developed into the functioning MVP.</p>
</section>

<section class="final-design prob fancier-final">
 <%= image_tag("fmocks.png") %>
  <p style="width: 70%; margin: 30px auto 0 auto; max-width: 1100px;">earlier design explorations. we ultimately choose to shift to a darker color scheme because of accessibility concerns and we felt the initial sahara desert inspired colors didn't match the trust and sense of confidence we wanted to build with our initial users</p>
</section>

<h2 class="decisions-text problem" style="margin-bottom: 20px; font-family: Proxima Nova Bold;">design <br> decisions 👩‍💻</h2>
<section class="problem">
  <%= image_tag("fmocks-1.png", class: "covid1") %>
  <div class="f-finding" style="align-self: center">
    <%= image_tag("fmarker1.svg") %>
    <p>We understood that sellers are frustrated because often in the sales funnel, customers are led away from their completing the purchse for competing offers. This also leads to a more chaotic user experience and the feeling of an endless marketplace which we wanted to avoid. We debated many possibilities but this is why we chose to include discoverability under posts but only of other articles by the seller to further create a seller centric experience on Fancier.</p>
  </div>
  <div class="f-finding" style="align-self: center">
    <%= image_tag("fmarker2.svg") %>
    <p>We chose to include a fixed filter to continue adding filter options during the scroll to further personalize the experience. Development wise, it was fairly complicated to implement the filters that I initially designed which was a learning experience to stay lean with UI.</p>
  </div>
  <%= image_tag("fmocks-2.png", class: "covid2") %>
  <%= image_tag("fmocks-3.png", class: "covid3") %>
  <div class="f-finding" style="align-self: center">
    <%= image_tag("fmarker3.svg") %>
    <p>We decided to model user profiles off of an instagram social media type UI because we wanted the experience to be community driven where people use fancier as not only to shopping destination but as a source of inspiration and ultimately build their profiles as a sense of identity.</p>
  </div>
</section>
<section class="problem">
  <h2>what i've <br>learned 📚</h2>
  <p><span>When you’re developing everything as well, you truly have a different hat on than when you’re only the designer. </span> when i designed a screen i also had in the forefront of my mind roughly how long it would take to develop, where the data was coming from and how that would impact the design, what was the “quick and dirty way” to implement and what was the better way. This mindset is one I keep always as a designer and why I’m passionate that designers should know enough code to be dangerous. If not, it's easy to fall into the trap of designing features with no regard of time to develop. During this project, I learned to create many, many iterations of my designs based on feedback and possibilities. I learned how to compromise aesthetics for functionality and time to develop at times such as the clothing filters that weren't the ideal UI but were much quicker to develop as dropdowns. I also learned to keep all different states in mind when I design.</p>
</section>
<h2 class="decisions-text problem" style="margin-bottom: 20px; font-family: Proxima Nova Bold;">other design + development work</h2>
<!-- <p class="">see my <a target=”_blank” href="https://github.com/meghanmartin995">github</a> for all dev work</p> -->
<!--   <div class="main-carousel" data-flickity='{ "cellAlign": "left", "contain": true, "imagesLoaded":true, "lazyLoad": true, "autoPlay": true}'>
    <div class="carousel-cell">
      <%#= image_tag("altura.gif", class: "") %>
    </div>

  </div> -->

<section class="final-design">
  <%=  image_tag("figma.gif", alt: "mockup of project", class: "") %>
  <p style="width: 50%; margin: 30px auto 0 auto; max-width: 1100px;">another design + dev project I have worked on is using the Figma API to create a living website of my style guide that updates whenever I change the Figma file or add additional frames</p>
</section>

<section class="final-design">
  <%=  image_tag("altura.gif", alt: "mockup of project", class: "") %>
  <p style="width: 50%; margin: 30px auto 0 auto; max-width: 1100px;">during Le Wagon bootcamp in a few day sprint I also designed and developed with a team of four Altura, a marketplace to rent private jets</p>
</section>

<!-- <section class="final-design">
  <%#=  image_tag("stock.gif", alt: "mockup of project", class: "") %>
  <p style="width: 50%; margin: 30px auto 0 auto; max-width: 1100px;">a dashboard to monitor stocks</p>
</section> -->

<footer class="project-footer">
  <%= link_to("previous project", covid_path) %>
  <a href="javascript:window.scrollTo(0,0);" style="cursor: pointer; text-decoration: none;" id="myBtn" title="Go to top">back to top</a>
  <%= link_to("next project", fonts_path) %>
</footer>

app/views/pages/fonts.html.erb
<header class="home-header project-head">
  <%= link_to root_path do %>
    <%=  image_tag("logo1.png", class: "logo") %>
  <% end %>
  <ul class="links page-links">
    <li> <a target=”_blank” href="https://www.linkedin.com/in/meghanxmartin/"><i aria-label="linkedin" class="fab fa-linkedin-in"></i></a> </li>
    <li> <a target=”_blank” href="https://twitter.com/meghanxmartin"><i aria-label="twitter" class="fab fa-twitter"></i></a> </li>
    <li> <a target=”_blank” href="https://github.com/meghanmartin995"><i aria-label="github" class="fab fa-github"></i></a> </li>
    <li> <a target=”_blank” href="https://dribbble.com/ziganka"><i aria-label="dribbble" class="fab fa-dribbble"></i></a> </li>
  </ul>
</header>

<header class="project-header fonts">
  <%=  image_tag("fitwmock.png", alt: "screenshot of project", class: "fancier-img img1 justify") %>
  <%=  image_tag("fitwmarks.svg", alt: "name of project", class: "fancier-M img2 justify") %>
  <div class="details">
    <p>2020</p>
    <p>UI Design | Design Resource</p>
  </div>
</header>

<section class="project-content">
  <div class="summary">
    <h2>Built a resource for the design community</h2>
    <p class="summary-text">designed and shipped a design resource to find both free and paid font inspiration for your next project. see the Product Hunt launch <a target=”_blank” href="https://www.producthunt.com/posts/fonts-in-the-wild">here, currently at #2 position for day of the launch</a></p>
  </div>
  <div class="project-role">
    <h3>Context</h3>
    <p><a target=”_blank” href="http://www.fontsinthewild.com/">live website</a>, with thousands of real users. currently designing + coding features such as filtering and sorting fonts for specific use cases and categories</p>
    <h3 class="role">Role</h3>
    <p>sole UI designer and fullstack developer. During quarantine I wanted to build a resource to give back to the design community and saw the gap in the market
    + challenge to find quality, open source fonts</p>
    <p class="team">This was a self initiated project.</p>
  </div>
</section>
<section class="final-design">
  <%=  image_tag("fitw.gif", alt: "mockup of project", class: "") %>
  <p>the final product</p>
</section>
<section class="problem">
  <h2>the problem ✍️</h2>
  <p>The core problem I am trying to solve with <a target=”_blank” style="text-decoration: underline;" href="http://www.fontsinthewild.com/">fonts in the wild </a>is the challenge of finding quality, free fonts. I spoke with many designers and developers who struggle to find free type inspiration. Current resources, such as Typewolf focus on expensive fonts with no option to filter through accessible options.</p>
</section>
<section class="final-design">
  <%=  image_tag("prob.jpg", alt: "problem landscape", class: "") %>
  <p style="width: 70%; margin: 30px auto 0 auto; max-width: 1100px;"><span style="font-weight: bold;">the problem landscape:</span> the primary insight from research & interviews is the challenge to find quality, open source fonts for commercial and personal work</p>
</section>
  <h2 class="decisions-text problem" style="margin-bottom: 20px; font-family: Proxima Nova Bold;">design <br> decisions 👩‍💻</h2>
<section class="decisions">
  <%= image_tag("fitwmm.jpg", class: "covid1") %>
  <div class="finding" style="align-self: center">
    <%= image_tag("marker-1.svg") %>
    <p>The filter options clearly demonstrate the value proposition of finding quality, open source fonts for both commercial and personal design work. I chose to create a Pinterest like feed with rounded playful corners and infinite scroll to encourage browsing for inspiration, keeping the frame narrow to maximize scannability. I added links to the websites on the home to minimize the amount of clicks to view the original design.</p>
  </div>
  <div class="finding2 finding" style="align-self: center">
    <%= image_tag("fitwmark.svg") %>
    <p>I chose to include a "you might also like" algorithm to quickly find similar font inspiration. I also chose to show the details of the post in a modal to quickly click left and right through modals and click out to continue scrolling.</p>
  </div>
  <%= image_tag("modal.jpg", class: "covid2") %>
</section>

<section class="problem">
  <h2>what i've <br>learned 📚</h2>
  <p>I've learned that the communication and launch of a product is more important than the design and code of it. I am continously learning how to best promote Fonts in the wild through different channels. I've also learned to keep things simple at first and launch the most minimal version of the product and iterate on feedback. I've also learned to design with the constraints of what I can develop but also to design without those limitations to push myself and grow beyond my current skillset.</p>
</section>

<section class="final-design" style="padding-top: 0px;">
  <iframe style="border: none;" src="https://cards.producthunt.com/cards/posts/224047?v=1" width="500" height="405" frameborder="0" scrolling="no" allowfullscreen></iframe>
</section>

<footer class="project-footer">
  <%= link_to("previous project", fancier_path) %>
  <a href="javascript:window.scrollTo(0,0);" style="cursor: pointer; text-decoration: none;" id="myBtn" title="Go to top">back to top</a>
  <%= link_to("next project", freelance_path) %>
</footer>

app/views/pages/freelance.html.erb
<header class="home-header project-head">
  <%= link_to root_path do %>
    <%=  image_tag("logo1.png", class: "logo") %>
  <% end %>
  <ul class="links page-links">
    <li> <a target=”_blank” href="https://www.linkedin.com/in/meghanxmartin/"><i aria-label="linkedin" class="fab fa-linkedin-in"></i></a> </li>
    <li> <a target=”_blank” href="https://twitter.com/meghanxmartin"><i aria-label="twitter" class="fab fa-twitter"></i></a> </li>
    <li> <a target=”_blank” href="https://github.com/meghanmartin995"><i aria-label="github" class="fab fa-github"></i></a> </li>
    <li> <a target=”_blank” href="https://dribbble.com/ziganka"><i aria-label="dribbble" class="fab fa-dribbble"></i></a> </li>
  </ul>
</header>

<header class="project-header freelance">
  <%=  image_tag("losarabis-l.png", alt: "screenshot of project", class: "fancier-img img1 justify") %>
  <%=  image_tag("freelancemarks.svg", alt: "name of project", class: "fancier-M img2 justify") %>
  <div class="details">
    <p>2020</p>
    <p>UI Design | Front end development</p>
  </div>
</header>

<section class="project-content">
  <div class="summary">
    <h2>Redesigning an outdated online store for a winery</h2>
    <p class="summary-text">redesigned multiple websites for freelance clients including an online wine store for Los Arabis Vineyards which I highlight here</p>
  </div>
  <div class="project-role">
    <h3>Context</h3>
    <p>live websites for freelance clients: <a target=”_blank” href="https://losarabisvineyards.com/">an online store</a>, <i>(highlighted here)</i>, <a target=”_blank” href="http://www.lamalpensatina.com/">a vacation property rental website</a>, <a target=”_blank” href="http://www.martinfamilyfound.com/"> a non profit landing page</a> </p>
    <h3 class="role">Role</h3>
    <p>UI designer and front end developer; custom Shopify development</p>
    <p class="team">These are freelance projects for clients.</p>
  </div>
</section>
<section class="final-design">
  <%=  image_tag("losarabis.gif", alt: "mockup of project", class: "") %>
  <p>the final product</p>
</section>
<section class="problem">
  <h2>the challenge ✍️</h2>
  <p>For this client, their current online store was not functioning at the payment stage and she needed a redesign of her website. Her website had been created over a decade ago in an antiquated program and she couldn't edit any products and customers couldn't finish the buying process. I researched the variety of solutions and we decided on the optimal solution technology wise taking into account the budget, timeframe, advantages and disadvantages. The target audience and goals of the redesign is to showcase and highlight the winery to restaurant and individual customers in the Bay Area, to increase restaurant contracts, sales channels and online sales of their wine.</p>
</section>

<section class="final-design">
  <%=  image_tag("lamood.jpg", alt: "mockup of project", class: "") %>
  <p>website moodboard</p>
</section>

<section class="problem">
  <h2>design process 👩‍💻</h2>
  <p>My process for freelance clients begins with a discovery meeting to deeply understand their business needs and current situation. Once we choose a direction, I scope the project and sent for her approval. To start the design I work back and forth with the client to audit their brand and create a moodboard of the feel of the website. Next, we go through websites on the market to understand their design preferences and build a common design language. Next I create a style guide for the website with colors, fonts and snippets of the future UI. Once this is approved, I create three mockup options and let the client choose the direction. From here, I move into final prototypes and ultimately the development phase. In this case, I created a custom Shopify store, but development varies case by case.</p>
</section>

<section class="final-design">
  <%=  image_tag("mockupsla.jpg", alt: "mockup of project", class: "") %>
  <p>three final mockup options</p>
</section>

<section class="problem">
  <h2>what i've <br>learned 📚</h2>
  <p>The biggest lesson I've learned through freelance work is that deeply understanding and listening to business challenges is the priority over the design itself. Often a client needs a business partner in strategy, not just a designer. This client on their previous website couldn't use other payments methods outside of Paypal so understanding this pain and offering solutions to take many payment providers was a huge first win.</p>
</section>

<footer class="project-footer">
  <%= link_to("previous project", fonts_path) %>
  <a href="javascript:window.scrollTo(0,0);" style="cursor: pointer; text-decoration: none;" id="myBtn" title="Go to top">back to top</a>
  <%= link_to("next project", thirtydays_path) %>
</footer>

app/views/posts/_like_link.html.erb
<%# vote_text = voter&.voted_for?(post) ? "Unlike" : "Like" %>

<%#= button_to vote_text, like_post_path(post), method: :put, remote: :true, class: 'like-post' %>

<% if @voter&.voted_for?(post) %>
  <%= button_to like_post_path(post), method: :put, remote: :true, id: "favorite-#{post.id}", class: 'like-post' do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= button_to like_post_path(post), method: :put, remote: :true, id: "favorite-#{post.id}", class: 'like-post' do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/posts/_likes.html.erb
<%= post.get_upvotes.size %>